import test from 'node:test';
import assert from 'node:assert/strict';
import {initializeApp,deleteApp} from 'firebase/app';
import {getAuth,connectAuthEmulator,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut} from 'firebase/auth';
import {getFirestore,connectFirestoreEmulator,doc,getDoc,setDoc,updateDoc,serverTimestamp} from 'firebase/firestore';
import {getAuth as adminAuth} from 'firebase-admin/auth';
import {getFirestore as adminDb} from 'firebase-admin/firestore';
import {ensureAccountProfile} from '../firebase-web/account-service.ts';
import {handle} from './lib/index.js';
const apps=[];
async function register(name,email){const app=initializeApp({projectId:'demo-orin-auth',apiKey:'test-api-key'},name);apps.push(app);const auth=getAuth(app),db=getFirestore(app);connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});connectFirestoreEmulator(db,'127.0.0.1',8080);const {user}=await createUserWithEmailAndPassword(auth,email,'Test-only-93!Password');await ensureAccountProfile(db,user);return {app,auth,db,user}}
async function api(c,path,method='GET',body,headers={}){let result,status=200;const token=c?await c.user.getIdToken():null;const req={path: path.split('?')[0],method,query:Object.fromEntries(new URLSearchParams(path.split('?')[1]??'')),body,get:k=>({'authorization':token?'Bearer '+token:undefined,origin:'https://orin-99951.web.app',...headers})[k.toLowerCase()],is:type=>type==='application/json'};const res={set(){return this},status(code){status=code;return this},json(value){result=value;return this}};await handle(req,res);return {status,body:result}}
const ok=r=>{assert.equal(r.status,200,JSON.stringify(r.body));return r.body};
test('Firebase original-app backend: identity, transactions, settings, notices and administration',async t=>{
 const owner=await register('owner','khtaub7341@gmail.com'),a=await register('member-a','a-'+Date.now()+'@example.test'),b=await register('member-b','b-'+Date.now()+'@example.test');
 try{
  await t.test('no anonymous, forged or unverified administrator access',async()=>{assert.equal((await api(null,'/api/lab')).status,401);assert.equal((await api(a,'/api/lab','GET',null,{authorization:'Bearer forged','oai-authenticated-user-id':owner.user.uid})).status,401);assert.equal((await api(owner,'/api/admin/notifications')).status,403);assert.equal((await api(a,'/api/admin/notifications')).status,403);assert.equal((await api(a,'/api/lab','GET',null,{origin:'https://attacker.test'})).status,403)});
  await adminAuth().updateUser(owner.user.uid,{emailVerified:true});await owner.user.getIdToken(true);await signOut(owner.auth);await signInWithEmailAndPassword(owner.auth,'khtaub7341@gmail.com','Test-only-93!Password');owner.user=owner.auth.currentUser;await ensureAccountProfile(owner.db,owner.user);
  await t.test('verified owner bootstraps admin, ordinary account does not',async()=>{assert.equal((await getDoc(doc(owner.db,'users',owner.user.uid))).data().role,'admin');assert.equal(ok(await api(owner,'/api/lab')).isAdmin,true);assert.equal(ok(await api(a,'/api/lab')).isAdmin,false);assert.equal(ok(await api(a,'/api/lab')).balanceCents,1000000);await assert.rejects(updateDoc(doc(a.db,'users',a.user.uid),{role:'admin',updatedAt:serverTimestamp()}));await assert.rejects(setDoc(doc(a.db,'orinAccounts',a.user.uid),{balanceCents:999999999}));await assert.rejects(setDoc(doc(owner.db,'orinContracts','forged'),{settlement_bps:1000}))});
  const now=Date.now(),terms={action:'publish',title:'Firebase integration',asset:'XAUUSD',direction:'BUY',durationSec:60,settlementBps:84,eligibility:'all',opensAt:now-1000,closesAt:now+86400000};
  let contract,position;
  await t.test('server authorization and concurrent allocation preserve balances',async()=>{assert.equal((await api(a,'/api/lab','POST',terms)).status,403);contract=ok(await api(owner,'/api/lab','POST',terms)).state.contracts[0];assert.equal(ok(await api(a,'/api/invitations/verify','POST',{code:contract.code})).contract.hash,contract.hash);const join={action:'join',code:contract.code,amountCents:900000,contractHash:contract.hash,confirmed:true};assert.equal((await api(a,'/api/lab','POST',join)).status,403);ok(await api(a,'/api/lab','POST',{action:'accept'}));const results=await Promise.all([api(a,'/api/lab','POST',join),api(a,'/api/lab','POST',join)]);results.forEach(ok);const s=ok(await api(a,'/api/lab'));assert.equal(s.balanceCents,100000);assert.equal(s.reservedCents,900000);assert.equal(s.positions.length,1);position=s.positions[0];assert.equal((await api(a,'/api/lab','POST',{...join,amountCents:100000})).status,409);assert.equal(ok(await api(b,'/api/lab')).positions.length,0);const other=ok(await api(owner,'/api/lab','POST',{...terms,title:'Overspend'})).state.contracts[0];assert.equal((await api(a,'/api/lab','POST',{...join,code:other.code,contractHash:other.hash,amountCents:200000})).status,409)});
  await t.test('settlement is idempotent and every journal is balanced',async()=>{const realNow=Date.now;Date.now=()=>position.ends_at+1;try{ok(await api(a,'/api/lab','POST',{action:'settle'}));ok(await api(a,'/api/lab','POST',{action:'settle'}));const s=ok(await api(a,'/api/lab'));assert.equal(s.balanceCents,1000000+7560);assert.equal(s.reservedCents,0);assert.equal(s.realizedCents,7560);assert.equal(s.receipts.length,1);assert.equal(s.positions[0].status,'settled');const journals=new Map();for(const entry of s.ledger)journals.set(entry.journal_id,(journals.get(entry.journal_id)??0)+entry.amount_cents);for(const sum of journals.values())assert.equal(sum,0)}finally{Date.now=realNow}});
  await t.test('settings persist, stale changes fail, and roles are not profile fields',async()=>{const s=ok(await api(a,'/api/settings'));const saved=ok(await api(a,'/api/settings','PATCH',{revision:s.revision,preferences:{theme:'dark',marketingNotifications:true},profile:{displayName:'ORIN verified test',country:'TR'}}));assert.equal(saved.preferences.theme,'dark');assert.equal(saved.profile.country,'TR');assert.equal((await api(a,'/api/settings','PATCH',{revision:s.revision,preferences:{theme:'light'}})).status,409);assert.equal((await api(a,'/api/settings','PATCH',{revision:saved.revision,profile:{role:'admin'}})).status,400);assert.equal((await api(a,'/api/settings','PATCH',{revision:saved.revision,preferences:{notificationEvents:{security:false}}})).status,409);assert.equal((await api(a,'/api/markets/configuration','PATCH',{revision:0,configuration:{}})).status,403)});
  await t.test('campaign previews, confirmation, opt-in, idempotency and per-user reads',async()=>{const campaign=ok(await api(owner,'/api/admin/notifications','POST',{action:'draft',title:'Test announcement',message:'Consent-based delivery',audience:{country:'TR',tier:'all',users:[]},language:'all',deepLink:'/notifications',startsAt:Date.now()-1000,expiresAt:Date.now()+86400000})).campaign;const preview=ok(await api(owner,'/api/admin/notifications','POST',{action:'preview',id:campaign.id}));assert.equal(preview.recipientCount,1);const send={action:'send',id:campaign.id,revision:campaign.revision,expectedRecipients:1,confirmed:true};assert.equal((await api(owner,'/api/admin/notifications','POST',{...send,confirmed:false})).status,409);ok(await api(owner,'/api/admin/notifications','POST',send));assert.equal((await api(owner,'/api/admin/notifications','POST',send)).status,409);const aa=ok(await api(a,'/api/notifications'));const notification=aa.items.find(n=>n.category==='announcement');assert.ok(notification);assert.equal(ok(await api(b,'/api/notifications?id='+encodeURIComponent(notification.id))).items.length,0);ok(await api(b,'/api/notifications','POST',{id:notification.id}));assert.equal(ok(await api(a,'/api/notifications?id='+encodeURIComponent(notification.id))).items[0].read_at,null);ok(await api(a,'/api/notifications','POST',{id:notification.id}));assert.ok(ok(await api(a,'/api/notifications?id='+encodeURIComponent(notification.id))).items[0].read_at);const s=ok(await api(a,'/api/settings'));ok(await api(a,'/api/settings','PATCH',{revision:s.revision,preferences:{marketingNotifications:false}}));assert.equal(ok(await api(a,'/api/notifications')).items.some(n=>n.category==='announcement'),false)});
  await t.test('disabled account cannot use backend despite a valid existing token',async()=>{await updateDoc(doc(owner.db,'users',a.user.uid),{disabled:true,updatedAt:serverTimestamp()});assert.equal((await api(a,'/api/lab')).status,403);assert.equal((await api(a,'/api/settings')).status,403);await assert.rejects(updateDoc(doc(owner.db,'users',owner.user.uid),{disabled:true,updatedAt:serverTimestamp()}));await updateDoc(doc(owner.db,'users',a.user.uid),{disabled:false,updatedAt:serverTimestamp()})});
 }finally{await Promise.all(apps.map(deleteApp))}
});
