/** Real ORIN session + MFA authority. All documents here are server-write-only. */
import {type DecodedIdToken} from 'firebase-admin/auth';
import {type Transaction} from 'firebase-admin/firestore';
import {adminApp as app, adminDb as securityDb, adminAuth as securityAuth} from './firebase-admin-init';
import {generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse} from '@simplewebauthn/server';
import {opaque,digest,equal,masterKey,seal,unseal,newTotpSecret,verifyTotp,newRecoveryCodes,recoveryHash,recoveryFormat,failureDelay,safeDevice} from './account-security-crypto';
import type {SecurityAction,SecurityDevice,SecuritySessionBundle,SecurityState} from '../../lib/account-security-types';
export {securityDb, securityAuth};
export class SecurityError extends Error{constructor(message:string,public status=400,public code='security-error'){super(message)}}
const db=securityDb,auth=securityAuth;
const doc=(c:string,id:string)=>db.collection(c).doc(id);
const profileRef=(uid:string)=>doc('orinAccountSecurity',uid);
const sessionRef=(sid:string)=>doc('orinSecuritySessions',sid);
const defaults={epoch:0,factorVersion:0,totpEnabled:false,recoveryHashes:[],lastTotpStep:-1,failures:0,blockedUntil:0};
const data=(s:any)=>({...defaults,...(typeof s?.data==='function'?(s.data()??{}):(s??{}))});
const key=()=>masterKey(process.env.ORIN_SECURITY_MASTER_KEY??'');
export const securityEnabled=()=>process.env.ORIN_ACCOUNT_SECURITY_ENABLED==='true';
export async function ensureSecurityActivation(requireEncryption=false){if(!securityEnabled())throw new SecurityError('خادم أمان ORIN غير مفعّل بعد.',503);if(requireEncryption)key();const marker=(await doc('system','account-security').get()).data();if(marker?.enabled!==true||marker?.rulesVersion!==160)throw new SecurityError('نشر قواعد حماية الحساب لم يكتمل بعد.',503);}
const SESSION_LIFE=30*86400_000,ACCESS_LIFE=3600_000,CHALLENGE_LIFE=5*60_000,STEPUP_LIFE=120_000;
const actions=new Set<SecurityAction>(['totp.enroll','totp.disable','recovery.regenerate','passkey.add','passkey.delete','trusted.add','trusted.delete','password.change','withdrawal.destination','withdrawal.submit']);
const actionName=(v:any):SecurityAction=>{if(!actions.has(v))throw new SecurityError('إجراء أمني غير صالح.');return v};
export type SecurityContext={uid:string;sid:string;session:any;token:DecodedIdToken;ip:string|null};
export type RequestMeta={ip:string|null;device?:SecurityDevice;providerValidAfter?:string;transportIP?:string|null;ipSource?:'direct'|'trusted-proxy'|'unavailable'};
function audit(tx:Transaction,uid:string,action:string,sid:string|null,ip:string|null,details:Record<string,string|number|boolean|null>={}){const id=opaque();tx.create(doc('orinSecurityEvents',id),{id,uid,action,sessionId:sid,ip,details,createdAt:Date.now()})}
async function availableUser(uid:string){const [user,p,access]=await Promise.all([auth.getUser(uid),doc('users',uid).get(),doc('orinControlAccess',uid).get()]);if(user.disabled||p.data()?.disabled||access.data()?.status==='suspended')throw new SecurityError('الحساب غير متاح.',403);return user}
export async function enforceSecuritySession(token:DecodedIdToken,accessToken?:string):Promise<any>{
 const sid=token.sid;if(typeof sid!=='string'||!/^[\w-]{43}$/.test(sid))throw new SecurityError('يجب إكمال تحقق جلسة ORIN.',401,'invalid-session');
 const [s,p]=await Promise.all([sessionRef(sid).get(),profileRef(token.uid).get()]);const session=s.data(),profile=data(p),now=Date.now();
 if(!session||session.uid!==token.uid||session.status!=='active'||session.expiresAtMs<=now||session.epoch!==profile.epoch||token.security_epoch!==profile.epoch)throw new SecurityError('انتهت الجلسة أو تم إبطالها.',401,'session-revoked');
 if(accessToken!==undefined&&(!/^[\w-]{43}$/.test(accessToken)||!((equal(session.accessHash,digest(accessToken))&&session.accessExpiresAt>now)||(session.previousAccessHash&&session.previousAccessUntil>now&&equal(session.previousAccessHash,digest(accessToken))))))throw new SecurityError('انتهى اعتماد الجلسة. يرجى تجديد الجلسة.',401,'session-expired');
 const providerUser=await availableUser(token.uid);if((providerUser.tokensValidAfterTime??'')!==(session.providerValidAfter??'')){await sessionRef(sid).update({status:'revoked',revokedAt:Date.now()});throw new SecurityError('أُبطلت الجلسة لدى موفّر تسجيل الدخول.',401,'session-revoked');}
 return session;
}
export async function context(header:string|undefined,access:string|undefined,meta:RequestMeta):Promise<SecurityContext>{
 if(!header?.startsWith('Bearer ')||!access)throw new SecurityError('سجّل الدخول للمتابعة.',401,'invalid-session');let token:DecodedIdToken;try{token=await auth.verifyIdToken(header.slice(7),true)}catch{throw new SecurityError('انتهت جلسة الدخول.',401,'session-expired')}
 const session=await enforceSecuritySession(token,access);await availableUser(token.uid);
 if(Date.now()-session.lastActiveAt>60_000)await sessionRef(String(token.sid)).update({lastActiveAt:Date.now()});
 return {uid:token.uid,sid:String(token.sid),session,token,ip:meta.ip};
}
function freshPrimary(token:DecodedIdToken,now=Date.now()){
 if(token.sid||token.firebase?.sign_in_provider==='custom'||!token.auth_time||now-token.auth_time*1000>120_000||token.auth_time*1000>now+30_000)throw new SecurityError('أعد التحقق من هويتك بكلمة المرور أولًا.',401,'recent-auth-required');
}
async function primary(raw:unknown,uid?:string){if(typeof raw!=='string'||raw.length>20000)throw new SecurityError('إعادة التحقق مطلوبة.',401);let t:DecodedIdToken;try{t=await auth.verifyIdToken(raw,true)}catch{throw new SecurityError('تعذر التحقق من بيانات الدخول.',401)}freshPrimary(t);if(uid&&t.uid!==uid)throw new SecurityError('إعادة التحقق لا تخص هذا الحساب.',403);const provider=await availableUser(t.uid);if(provider.tokensValidAfterTime&&Date.parse(provider.tokensValidAfterTime)>t.auth_time*1000)throw new SecurityError('أُبطل اعتماد الدخول.',401,'recent-auth-required');return t}
function factor(profile:any,input:any,uid:string,now:number){
 if(profile.blockedUntil>now)throw new SecurityError('محاولات كثيرة. حاول لاحقًا.',429);
 if(!profile.totpEnabled)return {ok:false,patch:{}};
 if(typeof input.otp==='string'){
  const step=verifyTotp(unseal(profile.totpCiphertext,key(),uid),input.otp,now,profile.lastTotpStep);
  if(step!==null)return {ok:true,patch:{lastTotpStep:step,failures:0,blockedUntil:0}};
 }
 if(recoveryFormat(input.recoveryCode)){const hash=recoveryHash(input.recoveryCode),hashes:string[]=profile.recoveryHashes??[];if(hashes.some(h=>equal(h,hash)))return {ok:true,patch:{recoveryHashes:hashes.filter(h=>!equal(h,hash)),failures:0,blockedUntil:0}}}
 const failures=(profile.failures??0)+1;return {ok:false,patch:{failures,blockedUntil:now+failureDelay(failures)}};
}
function sessionRecord(uid:string,epoch:number,meta:RequestMeta){const now=Date.now(),sid=opaque(),accessToken=opaque(),refreshToken=opaque();return {sid,accessToken,refreshToken,record:{uid,epoch,status:'active',createdAt:now,lastActiveAt:now,expiresAtMs:now+SESSION_LIFE,accessExpiresAt:now+ACCESS_LIFE,accessHash:digest(accessToken),refreshHash:digest(refreshToken),previousRefreshHash:null,device:safeDevice(meta.device),ip:meta.ip,ipSource:meta.ipSource??'unavailable',transportIP:meta.transportIP??null,approximateLocation:null,providerValidAfter:meta.providerValidAfter??''}}}
async function bundle(s:ReturnType<typeof sessionRecord>):Promise<SecuritySessionBundle>{return {sessionId:s.sid,accessToken:s.accessToken,refreshToken:s.refreshToken,expiresAt:s.record.expiresAtMs,accessExpiresAt:s.record.accessExpiresAt,customToken:await auth.createCustomToken(s.record.uid,{sid:s.sid,security_epoch:s.record.epoch})}}
export async function login(rawToken:string,input:any,meta:RequestMeta){
 const token=await primary(rawToken),uid=token.uid,challengeId=opaque(),now=Date.now(),claimId=digest(`${uid}:${token.auth_time}`),providerUser=await availableUser(uid);meta={...meta,providerValidAfter:providerUser.tokensValidAfterTime??''};await securityActorBudget(uid);let created:ReturnType<typeof sessionRecord>|null=null;
 const result=await db.runTransaction(async tx=>{
  const [p,used]=await Promise.all([tx.get(profileRef(uid)),tx.get(doc('orinSecurityPrimaryClaims',claimId))]);const profile=data(p);
  let trusted:any=null,trustRef:any=null;if(input.trustedDevice?.id&&input.trustedDevice?.deviceToken){trustRef=doc('orinTrustedDevices',identifier(input.trustedDevice.id));const td=await tx.get(doc('orinTrustedDevices',identifier(input.trustedDevice.id))),v=td.data();if(v&&v.uid===uid&&!v.revokedAt&&v.expiresAt>now&&v.epoch===profile.epoch&&equal(v.tokenHash,digest(identifier(input.trustedDevice.deviceToken))))trusted={id:td.id,...v};}
  if(used.exists)throw new SecurityError('أعد تسجيل الدخول؛ سبق استخدام اعتماد الدخول هذا.',401);
  tx.create(doc('orinSecurityPrimaryClaims',claimId),{uid,createdAt:now,expiresAt:now+SESSION_LIFE});
  if(!p.exists)tx.set(profileRef(uid),defaults);
  if(profile.totpEnabled&&!trusted){tx.create(doc('orinSecurityChallenges',challengeId),{uid,kind:'login',createdAt:now,expiresAt:now+CHALLENGE_LIFE,consumed:false,meta:{ip:meta.ip,device:safeDevice(input.device)},epoch:profile.epoch,providerValidAfter:meta.providerValidAfter,primaryAuthTime:token.auth_time});return {challengeId,requiresSecondFactor:true,methods:['totp','recovery']}}
  created=sessionRecord(uid,profile.epoch,{...meta,device:input.device});if(trusted){Object.assign(created.record,{trustedDeviceId:trusted.id});tx.update(trustRef,{lastUsedAt:now,sessionId:created.sid});}tx.create(sessionRef(created.sid),created.record);audit(tx,uid,'LOGIN_SUCCESS',created.sid,meta.ip,{factor:trusted?'trusted_device_and_primary':'primary'});if(!trusted)audit(tx,uid,'UNRECOGNIZED_DEVICE',created.sid,meta.ip);return null;
 });return created?bundle(created):result;
}
export async function completeLogin(input:any,meta:RequestMeta){
 const challengeId=identifier(input.challengeId),now=Date.now(),preChallenge=(await doc('orinSecurityChallenges',identifier(input.challengeId)).get()).data();if(!preChallenge?.uid)throw new SecurityError('انتهى طلب تسجيل الدخول.',401);const providerUser=await availableUser(preChallenge.uid);meta={...meta,providerValidAfter:providerUser.tokensValidAfterTime??''};let created:ReturnType<typeof sessionRecord>|null=null;
 const ok=await db.runTransaction(async tx=>{
  const challenge=await tx.get(doc('orinSecurityChallenges',challengeId)),c=challenge.data();if(!c||c.kind!=='login'||c.consumed||c.expiresAt<=now)throw new SecurityError('انتهى طلب تسجيل الدخول.',401);
  const p=await tx.get(profileRef(c.uid)),profile=data(p);if(c.providerValidAfter!==meta.providerValidAfter)throw new SecurityError('أُبطل اعتماد الدخول. سجّل الدخول مجددًا.',401,'recent-auth-required');if(c.epoch!==profile.epoch)throw new SecurityError('تم إبطال طلب الدخول.',401);
  const f=factor(profile,input,c.uid,now);tx.set(profileRef(c.uid),f.patch,{merge:true});
  if(!f.ok){audit(tx,c.uid,'LOGIN_FAILED',null,meta.ip,{reason:'second_factor'});return false}
  created=sessionRecord(c.uid,profile.epoch,{...meta,device:c.meta.device});tx.update(challenge.ref,{consumed:true});tx.create(sessionRef(created.sid),created.record);audit(tx,c.uid,'LOGIN_SUCCESS',created.sid,meta.ip,{factor:input.recoveryCode?'recovery':'totp'});audit(tx,c.uid,'UNRECOGNIZED_DEVICE',created.sid,meta.ip);return true;
 });if(!ok||!created)throw new SecurityError('رمز التحقق غير صحيح أو سبق استخدامه.',401,'invalid-otp');await availableUser((created as ReturnType<typeof sessionRecord>).record.uid);return bundle(created);
}
export async function refresh(input:any){
 const sid=identifier(input.sessionId),token=identifier(input.refreshToken),now=Date.now(),accessToken=opaque(),refreshToken=opaque();let record:any;
 const ok=await db.runTransaction(async tx=>{const s=await tx.get(sessionRef(sid)),v=s.data();if(!v)throw new SecurityError('الجلسة غير متاحة.',401,'invalid-session');const p=await tx.get(profileRef(v.uid));if(v.status!=='active'||v.expiresAtMs<=now||v.epoch!==data(p).epoch)throw new SecurityError('تم إبطال الجلسة.',401,'session-revoked');
  if(!equal(v.refreshHash,digest(token))){if(v.previousRefreshHash&&equal(v.previousRefreshHash,digest(token))){tx.update(s.ref,{status:'revoked',revokedAt:now});audit(tx,v.uid,'SESSION_REVOKED',sid,null,{reason:'refresh_replay'});}return false}
  record={...v,previousAccessHash:v.accessHash,previousAccessUntil:Math.min(v.accessExpiresAt,now+30_000),accessHash:digest(accessToken),accessExpiresAt:now+ACCESS_LIFE,refreshHash:digest(refreshToken),previousRefreshHash:v.refreshHash,lastActiveAt:now};tx.set(s.ref,record);return true;
 });if(!ok)throw new SecurityError('اعتماد تجديد الجلسة غير صالح.',401,'session-revoked');const providerUser=await availableUser(record.uid);if((providerUser.tokensValidAfterTime??'')!==(record.providerValidAfter??'')){await sessionRef(sid).update({status:'revoked',revokedAt:now});throw new SecurityError('أُبطلت الجلسة لدى موفّر تسجيل الدخول.',401,'session-revoked');}return bundle({sid,accessToken,refreshToken,record});
}
export function identifier(v:any){if(typeof v!=='string'||!/^[\w-]{43}$/.test(v))throw new SecurityError('معرّف غير صالح.');return v}
async function assertSessionTx(tx:Transaction,c:{uid:string;sid:string}){const [s,p]=await Promise.all([tx.get(sessionRef(c.sid)),tx.get(profileRef(c.uid))]);const v=s.data();if(!v||v.uid!==c.uid||v.status!=='active'||v.expiresAtMs<=Date.now()||v.epoch!==data(p).epoch)throw new SecurityError('تم إبطال الجلسة.',401,'session-revoked');return data(p)}
async function all(c:string,uid:string){return (await db.collection(c).where('uid','==',uid).get()).docs.map(d=>({id:d.id,...d.data()} as any))}
export async function state(c:SecurityContext):Promise<SecurityState>{
 const [p,sessions,keys,trusted,events]=await Promise.all([profileRef(c.uid).get(),all('orinSecuritySessions',c.uid),all('orinSecurityPasskeys',c.uid),all('orinTrustedDevices',c.uid),all('orinSecurityEvents',c.uid)]),v=data(p),now=Date.now();
 return {available:true,totp:{enabled:v.totpEnabled===true},recoveryCodes:{remaining:v.recoveryHashes?.length??0},sessions:sessions.filter(s=>s.status==='active'&&s.expiresAtMs>now&&s.epoch===v.epoch).map(s=>({id:s.id,device:s.device,createdAt:s.createdAt,lastActiveAt:s.lastActiveAt,expiresAt:s.expiresAtMs,ip:s.ip,ipSource:s.ipSource??'unavailable',approximateLocation:null,current:s.id===c.sid,status:'active'})),passkeys:keys.filter(k=>!k.revokedAt).map(k=>({id:k.id,name:k.name,createdAt:k.createdAt,lastUsedAt:k.lastUsedAt??null})),trustedDevices:trusted.filter(t=>!t.revokedAt&&t.expiresAt>now&&t.epoch===v.epoch).map(t=>({id:t.id,name:t.name,createdAt:t.createdAt,lastUsedAt:t.lastUsedAt,current:t.sessionId===c.sid})),events:events.sort((a,b)=>b.createdAt-a.createdAt).slice(0,100).map(({id,action,createdAt,sessionId,ip,details})=>({id,action,createdAt,sessionId,ip,details})),capabilities:{passkeys:!!process.env.ORIN_WEBAUTHN_RP_ID,geoIP:false}};
}
export async function revoke(c:SecurityContext,target:string|'others'){
 const rows=target==='others'?(await all('orinSecuritySessions',c.uid)).filter(s=>s.id!==c.sid&&s.status==='active'):[{id:identifier(target)}];
 for(const row of rows)await db.runTransaction(async tx=>{const s=await tx.get(sessionRef(row.id));if(s.data()?.uid!==c.uid)throw new SecurityError('الجلسة لا تخص هذا الحساب.',403);tx.update(s.ref,{status:'revoked',revokedAt:Date.now()});audit(tx,c.uid,'SESSION_REVOKED',c.sid,c.ip,{target:row.id});});return {ok:true};
}
export async function stepUp(c:SecurityContext,input:any){
 const action=actionName(input.action),now=Date.now(),stepUpToken=opaque();let primaryVerified=false;
 if(input.freshFirebaseToken){await primary(input.freshFirebaseToken,c.uid);primaryVerified=true}
 const ok=await db.runTransaction(async tx=>{await assertSessionTx(tx,c);const p=await tx.get(profileRef(c.uid)),v=data(p);let ok=primaryVerified,patch={};if(v.totpEnabled){const f=factor(v,input,c.uid,now);ok=f.ok;patch=f.patch;}if(Object.keys(patch).length)tx.set(p.ref,patch,{merge:true});if(!ok){audit(tx,c.uid,'STEP_UP_FAILED',c.sid,c.ip,{action});return false}tx.create(doc('orinSecurityGrants',digest(stepUpToken)),{uid:c.uid,sid:c.sid,epoch:v.epoch,factorVersion:v.factorVersion,action,expiresAt:now+STEPUP_LIFE,consumed:false});return true});
 if(!ok)throw new SecurityError('إعادة التحقق الأمني مطلوبة.',401,'recent-auth-required');return {stepUpToken,expiresAt:now+STEPUP_LIFE};
}
export async function consumeSecurityGrant(tx:Transaction,c:{uid:string;sid:string},token:string,action:SecurityAction){
 identifier(token);const g=await tx.get(doc('orinSecurityGrants',digest(token))),v=g.data();const [p,s]=await Promise.all([tx.get(profileRef(c.uid)),tx.get(sessionRef(c.sid))]);
 if(s.data()?.uid!==c.uid||s.data()?.status!=='active'||s.data()!.expiresAtMs<=Date.now()||s.data()?.epoch!==data(p).epoch)throw new SecurityError('تم إبطال الجلسة.',401,'session-revoked');
 if(!v||v.uid!==c.uid||v.sid!==c.sid||v.action!==action||v.epoch!==data(p).epoch||(v.factorVersion??0)!==data(p).factorVersion||v.consumed||v.expiresAt<=Date.now())throw new SecurityError('إعادة التحقق مطلوبة لهذا الإجراء.',403);return ()=>tx.update(g.ref,{consumed:true,consumedAt:Date.now()});
}
/** Consume inside the same transaction as the protected write whenever possible. */
export async function requireSecurityStepUp(token:DecodedIdToken,grant:string,action:SecurityAction){await enforceSecuritySession(token);await db.runTransaction(async tx=>{const consume=await consumeSecurityGrant(tx,{uid:token.uid,sid:String(token.sid)},grant,action);consume()});}
export async function enrollTotp(c:SecurityContext,input:any){
 const enrollmentId=opaque(),secret=newTotpSecret(),now=Date.now(),ciphertext=seal(secret,key(),c.uid);
 await db.runTransaction(async tx=>{const p=await tx.get(profileRef(c.uid));if(data(p).totpEnabled)throw new SecurityError('المصادقة الثنائية مفعّلة بالفعل.',409);const consume=await consumeSecurityGrant(tx,c,input.stepUpToken,'totp.enroll');consume();tx.set(doc('orinTotpEnrollments',c.uid),{uid:c.uid,sid:c.sid,enrollmentId,ciphertext,expiresAt:now+CHALLENGE_LIFE,attempts:0});});
 return {enrollmentId,secret,otpauthUri:`otpauth://totp/ORIN:${encodeURIComponent(c.token.email??c.uid)}?secret=${secret}&issuer=ORIN&algorithm=SHA1&digits=6&period=30`};
}
export async function verifyEnrollment(c:SecurityContext,input:any){
 const enrollmentId=identifier(input.enrollmentId),now=Date.now(),codes=newRecoveryCodes();const ok=await db.runTransaction(async tx=>{await assertSessionTx(tx,c);const [e,p]=await Promise.all([tx.get(doc('orinTotpEnrollments',c.uid)),tx.get(profileRef(c.uid))]),v=e.data(),profile=data(p);
  const sessions=await tx.get(db.collection('orinSecuritySessions').where('uid','==',c.uid)),trusted=await tx.get(db.collection('orinTrustedDevices').where('uid','==',c.uid));
  if(!v||v.sid!==c.sid||v.enrollmentId!==enrollmentId||v.expiresAt<=now||v.attempts>=5||profile.totpEnabled)throw new SecurityError('انتهى طلب التفعيل. ابدأ من جديد.',409);
  const step=verifyTotp(unseal(v.ciphertext,key(),c.uid),String(input.otp??''),now);if(step===null){tx.update(e.ref,{attempts:v.attempts+1});audit(tx,c.uid,'TOTP_ENROLLMENT_FAILED',c.sid,c.ip);return false}
  tx.set(p.ref,{totpEnabled:true,factorVersion:profile.factorVersion+1,totpCiphertext:v.ciphertext,lastTotpStep:step,recoveryHashes:codes.map(recoveryHash),failures:0,blockedUntil:0,totpEnabledAt:now},{merge:true});tx.delete(e.ref);trusted.docs.forEach(t=>tx.update(t.ref,{revokedAt:now}));sessions.docs.filter(s=>s.id!==c.sid&&s.data().status==='active').forEach(s=>tx.update(s.ref,{status:'revoked',revokedAt:now}));audit(tx,c.uid,'TOTP_ENABLED',c.sid,c.ip);audit(tx,c.uid,'RECOVERY_CODES_CREATED',c.sid,c.ip,{count:codes.length});return true;
 });if(!ok)throw new SecurityError('رمز التحقق غير صحيح.',400,'invalid-otp');return {ok:true,recoveryCodes:codes};
}
export async function disableTotp(c:SecurityContext,input:any){await db.runTransaction(async tx=>{const profile=data(await tx.get(profileRef(c.uid)));const consume=await consumeSecurityGrant(tx,c,input.stepUpToken,'totp.disable');const rows=await tx.get(db.collection('orinTrustedDevices').where('uid','==',c.uid));consume();tx.set(profileRef(c.uid),{totpEnabled:false,factorVersion:profile.factorVersion+1,totpCiphertext:null,recoveryHashes:[],lastTotpStep:-1},{merge:true});rows.docs.forEach(d=>tx.update(d.ref,{revokedAt:Date.now()}));audit(tx,c.uid,'TOTP_DISABLED',c.sid,c.ip);});return {ok:true}}
export async function regenerateRecovery(c:SecurityContext,input:any){const codes=newRecoveryCodes();await db.runTransaction(async tx=>{const p=await tx.get(profileRef(c.uid));if(!data(p).totpEnabled)throw new SecurityError('فعّل المصادقة الثنائية أولًا.',409);const consume=await consumeSecurityGrant(tx,c,input.stepUpToken,'recovery.regenerate');consume();tx.set(p.ref,{recoveryHashes:codes.map(recoveryHash)},{merge:true});audit(tx,c.uid,'RECOVERY_CODES_CREATED',c.sid,c.ip,{count:codes.length});});return {recoveryCodes:codes}}
export async function addTrusted(c:SecurityContext,input:any){const id=opaque(),deviceToken=opaque(),now=Date.now();await db.runTransaction(async tx=>{const consume=await consumeSecurityGrant(tx,c,input.stepUpToken,'trusted.add');consume();tx.create(doc('orinTrustedDevices',id),{uid:c.uid,sessionId:c.sid,name:safeDevice({label:input.name??c.session.device.label}).label,tokenHash:digest(deviceToken),createdAt:now,lastUsedAt:now,expiresAt:now+SESSION_LIFE,epoch:c.session.epoch,revokedAt:null});audit(tx,c.uid,'TRUSTED_DEVICE_ADDED',c.sid,c.ip,{deviceId:id});});return {id,deviceToken,expiresAt:now+SESSION_LIFE}}
export async function proveTrusted(c:SecurityContext,input:any){const id=identifier(input.id),proof=identifier(input.deviceToken);await db.runTransaction(async tx=>{const d=await tx.get(doc('orinTrustedDevices',id)),v=d.data();if(!v||v.uid!==c.uid||v.revokedAt||v.expiresAt<=Date.now()||v.epoch!==c.session.epoch||!equal(v.tokenHash,digest(proof)))throw new SecurityError('هذا الجهاز غير موثوق. يلزم التحقق الأمني.',403);tx.update(d.ref,{lastUsedAt:Date.now(),sessionId:c.sid});});return {trusted:true}}
export async function deleteTrusted(c:SecurityContext,input:any){const id=identifier(input.id);await db.runTransaction(async tx=>{const d=await tx.get(doc('orinTrustedDevices',id));if(d.data()?.uid!==c.uid)throw new SecurityError('الجهاز غير موجود.',404);const consume=await consumeSecurityGrant(tx,c,input.stepUpToken,'trusted.delete');const sessions=await tx.get(db.collection('orinSecuritySessions').where('uid','==',c.uid));consume();tx.update(d.ref,{revokedAt:Date.now()});sessions.docs.filter(s=>s.data().trustedDeviceId===id).forEach(s=>tx.update(s.ref,{status:'revoked',revokedAt:Date.now()}));audit(tx,c.uid,'TRUSTED_DEVICE_REMOVED',c.sid,c.ip,{deviceId:id});});return {ok:true}}
export async function changePassword(c:SecurityContext,input:any){
 if(typeof input.password!=='string'||input.password.length<12||input.password.length>128)throw new SecurityError('استخدم كلمة مرور من 12 إلى 128 حرفًا.');
 await db.runTransaction(async tx=>{const consume=await consumeSecurityGrant(tx,c,input.stepUpToken,'password.change');consume()});await auth.updateUser(c.uid,{password:input.password});await auth.revokeRefreshTokens(c.uid);
 await db.runTransaction(async tx=>{const p=await tx.get(profileRef(c.uid));tx.set(p.ref,{epoch:data(p).epoch+1},{merge:true});audit(tx,c.uid,'PASSWORD_CHANGED',c.sid,c.ip);});return {ok:true,requiresLogin:true};
}
const rp=()=>{const rpID=process.env.ORIN_WEBAUTHN_RP_ID,origin=process.env.ORIN_WEBAUTHN_ORIGIN;if(!rpID||!origin||new URL(origin).protocol!=='https:'||new URL(origin).hostname!==rpID)throw new SecurityError('لم يُضبط نطاق مفاتيح المرور الآمن بعد.',503);return {rpID,origin}}
export async function passkeyOptions(c:SecurityContext,input:any){
 const {rpID,origin}=rp(),keys=await all('orinSecurityPasskeys',c.uid),challengeId=opaque(),now=Date.now();
 const options=await generateRegistrationOptions({rpName:'ORIN',rpID,userID:new Uint8Array(Buffer.from(digest(c.uid),'hex')),userName:c.token.email??c.uid,attestationType:'none',excludeCredentials:keys.filter(k=>!k.revokedAt).map(k=>({id:k.credentialId})),authenticatorSelection:{residentKey:'required',userVerification:'required'},supportedAlgorithmIDs:[-7,-257]});
 await db.runTransaction(async tx=>{const factorVersion=data(await tx.get(profileRef(c.uid))).factorVersion;const consume=await consumeSecurityGrant(tx,c,input.stepUpToken,'passkey.add');consume();tx.create(doc('orinSecurityChallenges',challengeId),{uid:c.uid,sid:c.sid,kind:'register',challenge:options.challenge,origin,rpID,expiresAt:now+CHALLENGE_LIFE,consumed:false,name:safeDevice({label:input.name||'Passkey'}).label,epoch:c.session.epoch,factorVersion});});return {challengeId,options};
}
async function consumeChallenge(c:SecurityContext,id:string,kind:string){return db.runTransaction(async tx=>{const profile=await assertSessionTx(tx,c);const d=await tx.get(doc('orinSecurityChallenges',identifier(id))),v=d.data();if(!v||v.uid!==c.uid||v.sid!==c.sid||v.kind!==kind||v.epoch!==c.session.epoch||(v.factorVersion??0)!==profile.factorVersion||v.consumed||v.expiresAt<=Date.now())throw new SecurityError('انتهى التحقق الأمني. ابدأ من جديد.',401);tx.update(d.ref,{consumed:true});return v});}
export async function verifyPasskey(c:SecurityContext,input:any){
 const challenge=await consumeChallenge(c,input.challengeId,'register');let result;try{result=await verifyRegistrationResponse({response:input.response,expectedChallenge:challenge.challenge,expectedOrigin:challenge.origin,expectedRPID:challenge.rpID,requireUserVerification:true,supportedAlgorithmIDs:[-7,-257]})}catch{throw new SecurityError('تعذر التحقق من مفتاح المرور.',400)}
 if(!result.verified||!result.registrationInfo)throw new SecurityError('لم يتم التحقق من مفتاح المرور.',400);const info=result.registrationInfo,credential=info.credential,id=digest(credential.id),now=Date.now();
 await db.runTransaction(async tx=>{const profile=await assertSessionTx(tx,c);if((challenge.factorVersion??0)!==profile.factorVersion)throw new SecurityError('تغيرت إعدادات الأمان. أعد التحقق.',409);const existing=await tx.get(doc('orinSecurityPasskeys',id));if(existing.exists)throw new SecurityError('مفتاح المرور مسجل مسبقًا.',409);tx.create(existing.ref,{uid:c.uid,credentialId:credential.id,publicKey:Buffer.from(credential.publicKey).toString('base64url'),counter:credential.counter,transports:credential.transports??[],name:challenge.name,createdAt:now,lastUsedAt:null,revokedAt:null});audit(tx,c.uid,'PASSKEY_ADDED',c.sid,c.ip,{passkeyId:id});});return {ok:true,id};
}
export async function deletePasskey(c:SecurityContext,input:any){const id=String(input.id??'');if(!/^[a-f0-9]{64}$/.test(id))throw new SecurityError('معرّف غير صالح.');await db.runTransaction(async tx=>{const d=await tx.get(doc('orinSecurityPasskeys',id));if(d.data()?.uid!==c.uid)throw new SecurityError('المفتاح غير موجود.',404);const consume=await consumeSecurityGrant(tx,c,input.stepUpToken,'passkey.delete');consume();tx.update(d.ref,{revokedAt:Date.now()});audit(tx,c.uid,'PASSKEY_REMOVED',c.sid,c.ip,{passkeyId:id});});return {ok:true}}
export async function passkeyAuthOptions(c:SecurityContext,input:any){const factorVersion=data(await profileRef(c.uid).get()).factorVersion;const {rpID,origin}=rp(),action=actionName(input.action),keys=(await all('orinSecurityPasskeys',c.uid)).filter(k=>!k.revokedAt);if(!keys.length)throw new SecurityError('لا توجد مفاتيح مرور مسجلة.',409);const options=await generateAuthenticationOptions({rpID,userVerification:'required',allowCredentials:keys.map(k=>({id:k.credentialId,transports:k.transports}))}),challengeId=opaque();await doc('orinSecurityChallenges',challengeId).create({uid:c.uid,sid:c.sid,kind:'authenticate',factorVersion,action,challenge:options.challenge,origin,rpID,expiresAt:Date.now()+CHALLENGE_LIFE,consumed:false,epoch:c.session.epoch});return {challengeId,options}}
export async function verifyPasskeyAuth(c:SecurityContext,input:any){const challenge=await consumeChallenge(c,input.challengeId,'authenticate'),id=digest(String(input.response?.id??'')),d=await doc('orinSecurityPasskeys',id).get(),v=d.data();if(!v||v.uid!==c.uid||v.revokedAt)throw new SecurityError('مفتاح المرور غير صالح.',403);let result;try{result=await verifyAuthenticationResponse({response:input.response,expectedChallenge:challenge.challenge,expectedOrigin:challenge.origin,expectedRPID:challenge.rpID,credential:{id:v.credentialId,publicKey:Buffer.from(v.publicKey,'base64url'),counter:v.counter,transports:v.transports},requireUserVerification:true})}catch{throw new SecurityError('تعذر التحقق من مفتاح المرور.',401)}if(!result.verified)throw new SecurityError('فشل التحقق من المفتاح.',401);const stepUpToken=opaque(),now=Date.now();await db.runTransaction(async tx=>{const profile=await assertSessionTx(tx,c);const fresh=await tx.get(d.ref);if(fresh.data()?.revokedAt||fresh.data()?.counter!==v.counter)throw new SecurityError('تغير مفتاح المرور. أعد المحاولة.',409);tx.update(d.ref,{counter:result.authenticationInfo.newCounter,lastUsedAt:now});tx.create(doc('orinSecurityGrants',digest(stepUpToken)),{uid:c.uid,sid:c.sid,epoch:c.session.epoch,factorVersion:profile.factorVersion,action:challenge.action,expiresAt:now+STEPUP_LIFE,consumed:false});});return {stepUpToken,expiresAt:now+STEPUP_LIFE}}
/** Passwordless login: discoverable credential + required authenticator user verification. */
export async function passkeyLoginOptions(meta:RequestMeta){const {rpID,origin}=rp(),challengeId=opaque(),options=await generateAuthenticationOptions({rpID,userVerification:'required'});await doc('orinSecurityChallenges',challengeId).create({kind:'passkey-login',challenge:options.challenge,origin,rpID,expiresAt:Date.now()+CHALLENGE_LIFE,consumed:false});return {challengeId,options}}
export async function passkeyLoginVerify(input:any,meta:RequestMeta){
 const challenge=await db.runTransaction(async tx=>{const d=await tx.get(doc('orinSecurityChallenges',identifier(input.challengeId))),v=d.data();if(!v||v.kind!=='passkey-login'||v.consumed||v.expiresAt<=Date.now())throw new SecurityError('انتهى طلب الدخول.',401);tx.update(d.ref,{consumed:true});return v});
 const id=digest(String(input.response?.id??'')),d=await doc('orinSecurityPasskeys',id).get(),v=d.data();if(!v||v.revokedAt)throw new SecurityError('مفتاح المرور غير صالح.',401);const providerUser=await availableUser(v.uid);meta={...meta,providerValidAfter:providerUser.tokensValidAfterTime??''};let result;
 try{result=await verifyAuthenticationResponse({response:input.response,expectedChallenge:challenge.challenge,expectedOrigin:challenge.origin,expectedRPID:challenge.rpID,credential:{id:v.credentialId,publicKey:Buffer.from(v.publicKey,'base64url'),counter:v.counter,transports:v.transports},requireUserVerification:true})}catch{await db.runTransaction(async tx=>{audit(tx,v.uid,'LOGIN_FAILED',null,meta.ip,{reason:'passkey'})});throw new SecurityError('تعذر التحقق من مفتاح المرور.',401)}
 if(!result.verified)throw new SecurityError('مفتاح المرور غير صالح.',401);let created:ReturnType<typeof sessionRecord>|null=null;
 await db.runTransaction(async tx=>{const [f,p]=await Promise.all([tx.get(d.ref),tx.get(profileRef(v.uid))]);if(f.data()?.revokedAt||f.data()?.counter!==v.counter)throw new SecurityError('تغير المفتاح. أعد المحاولة.',409);created=sessionRecord(v.uid,data(p).epoch,{...meta,device:input.device});tx.update(d.ref,{counter:result.authenticationInfo.newCounter,lastUsedAt:Date.now()});tx.create(sessionRef(created.sid),created.record);audit(tx,v.uid,'LOGIN_SUCCESS',created.sid,meta.ip,{factor:'passkey'});});return bundle(created!);
}
/** Shared per-IP endpoint budget; keys are IP hashes and never contain credentials. */
export async function securityRequestBudget(ip:string|null){if(!ip)return;return securityBudget('ip:'+ip,300)}
export async function securityActorBudget(uid:string){return securityBudget('uid:'+uid,60)}
async function securityBudget(scope:string,limit:number){const now=Date.now(),id=digest(scope);await db.runTransaction(async tx=>{const d=await tx.get(doc('orinSecurityRateLimits',id)),v=d.data(),reset=now-(v?.windowStart??0)>=60_000;if(!reset&&(v?.count??0)>=limit)throw new SecurityError('محاولات كثيرة. حاول بعد دقيقة.',429);tx.set(d.ref,{windowStart:reset?now:v!.windowStart,count:reset?1:v!.count+1,expiresAt:now+60_000});});}
