/** Server-only integration boundary. Never expose these methods as client-callable endpoints.
 * Invoke only AFTER the payment/KYC/broker adapter verifies its provider signature and final status.
 * Provider adapters must authenticate and reconcile their events before calling this boundary.
 */
import {db,ref,hash,ApiError,audit,type Data} from './store';
const key=(s:string)=>{if(!/^[a-zA-Z0-9_-]{1,128}$/.test(s))throw new ApiError('Invalid trusted event id');return s};
const validMoney=(n:number)=>Number.isSafeInteger(n)&&n>=0&&n<=Number.MAX_SAFE_INTEGER/4;
export async function recordVerifiedCustomer(uid:string,customerKey:string,eventId:string){
 key(uid);key(eventId);if(!/^[a-f0-9]{64}$/.test(customerKey))throw new ApiError('Use an irreversible provider customer fingerprint');
 await db.runTransaction(async tx=>{const event=ref('orinTrustedEvents',eventId),v=ref('orinVerifiedCustomers',uid),unique=ref('orinCustomerRegistry',customerKey),member=ref('orinProgramMembers',uid);const [old,owner,m]=await Promise.all([tx.get(event),tx.get(unique),tx.get(member)]);const fingerprint=hash(JSON.stringify({uid,customerKey}));if(old.exists){if(old.data()!.fingerprint!==fingerprint)throw new ApiError('Event conflict',409);return}if(owner.exists&&owner.data()!.uid!==uid)throw new ApiError('Duplicate customer',409);const existing=await tx.get(v);if(existing.exists&&existing.data()!.customerKey!==customerKey)throw new ApiError('Verification identity changed; review required',409);tx.set(unique,{uid});tx.set(v,{uid,customerKey,verified:true,revoked:false,eventId});if(m.exists)tx.update(member,{badges:[...new Set([...(m.data()!.badges??[]),'verified'])]});tx.create(event,{fingerprint,type:'verification',uid});audit(tx,'trusted-'+eventId,'provider','CUSTOMER_VERIFIED',uid,{eventId},Date.now())});
}
export async function recordConfirmedDeposit(e:{eventId:string;uid:string;accountId:string;currency:'USD';cents:number;eligible:boolean}){
 key(e.eventId);key(e.uid);key(e.accountId);if(e.currency!=='USD'||!validMoney(e.cents)||e.cents===0||typeof e.eligible!=='boolean')throw new ApiError('Invalid confirmed deposit');
 await db.runTransaction(async tx=>{const event=ref('orinTrustedEvents',e.eventId),a=db.doc(`sparkTradingAccounts/${e.uid}/accounts/${e.accountId}`),b=ref('orinBonusWallets',e.uid),fund=ref('orinQualifiedDeposits',e.uid),m=ref('orinProgramMembers',e.uid);const [old,acc,bonus,first,member,profile,access]=await Promise.all([tx.get(event),tx.get(a),tx.get(b),tx.get(fund),tx.get(m),tx.get(ref('users',e.uid)),tx.get(ref('orinControlAccess',e.uid))]);const fingerprint=hash(JSON.stringify(e));if(old.exists){if(old.data()!.fingerprint!==fingerprint)throw new ApiError('Event conflict',409);return}if(!profile.exists||profile.data()!.disabled||access.data()?.status==='suspended')throw new ApiError('Funding account restricted',409);const data=acc.data();if(!data||data.ownerId!==e.uid||data.type!=='real'||data.currency!=='USD'||!validMoney(data.balanceCents+e.cents))throw new ApiError('Invalid funding account',409);
  // Deposits remain customer cash. Separate sub-threshold deposits are never added to unlock the bonus.
  tx.update(a,{balanceCents:data.balanceCents+e.cents});const legacy=ref('orinAccounts',e.uid);const legSnap=await tx.get(legacy);if(legSnap.exists){tx.update(legacy,{balanceCents:(legSnap.data()?.balanceCents??0)+e.cents,updated_at:Date.now()});}
  if(e.eligible&&(!first.exists||e.cents>first.data()!.cents)){tx.set(fund,{uid:e.uid,eventId:e.eventId,cents:e.cents,accountId:e.accountId});if(bonus.exists)tx.update(b,{qualifiedDepositCents:e.cents,withdrawableProfitCents:e.cents>=(bonus.data()!.firstDepositCents??50000)?bonus.data()!.profitCents:0});}
  if(member.exists)tx.update(m,{badges:[...new Set([...(member.data()!.badges??[]),'first_deposit'])]});
  tx.create(event,{...e,fingerprint,type:'deposit',status:'confirmed'});tx.create(ref('orinProgramLedger','deposit-'+e.eventId),{uid:e.uid,accountId:e.accountId,kind:'deposit',entries:[{account:'cash',cents:e.cents},{account:'payment-clearing',cents:-e.cents}],createdAt:Date.now()});audit(tx,'trusted-'+e.eventId,'provider','DEPOSIT_CONFIRMED',e.uid,{eventId:e.eventId,cents:e.cents,accountId:e.accountId},Date.now());
 });
}
export async function recordFinalBonusProfit(e:{eventId:string;uid:string;accountId:string;asset:string;profitCents:number;closedAt:number}){
 key(e.eventId);key(e.uid);key(e.accountId);if(!validMoney(e.profitCents)||!Number.isSafeInteger(e.closedAt))throw new ApiError('Invalid finalized net profit');
 await db.runTransaction(async tx=>{const event=ref('orinTrustedEvents',e.eventId),b=ref('orinBonusWallets',e.uid),m=ref('orinProgramMembers',e.uid);const [old,w,member,v]=await Promise.all([tx.get(event),tx.get(b),tx.get(m),tx.get(ref('orinVerifiedCustomers',e.uid))]);const fingerprint=hash(JSON.stringify(e));if(old.exists){if(old.data()!.fingerprint!==fingerprint)throw new ApiError('Event conflict',409);return}const d=w.data();if(!d||d.accountId!==e.accountId||!v.data()?.verified||v.data()?.revoked||e.closedAt<d.claimedAt||e.closedAt>d.expiresAt||!d.eligibleAssets.includes(e.asset))throw new ApiError('Trade not eligible',409);const profit=d.profitCents+e.profitCents;if(!validMoney(profit)||profit>d.profitLimitCents)throw new ApiError('Configured profit cap exceeded; review required',409);tx.update(b,{profitCents:profit,withdrawableProfitCents:d.qualifiedDepositCents>=(d.firstDepositCents??50000)?profit:0});if(member.exists)tx.update(m,{badges:[...new Set([...(member.data()!.badges??[]),'trader'])]});tx.create(event,{...e,fingerprint,type:'bonus_profit'});tx.create(ref('orinProgramLedger','profit-'+e.eventId),{uid:e.uid,accountId:e.accountId,kind:'bonus_profit',entries:[{account:'bonus-profit',cents:e.profitCents},{account:'broker-clearing',cents:-e.profitCents}],createdAt:Date.now()});audit(tx,'trusted-'+e.eventId,'broker','BONUS_PROFIT_CONFIRMED',e.uid,{eventId:e.eventId,profitCents:e.profitCents},Date.now())});
}
